service: lambda-redis-tec-guru

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-2

functions:
  api:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'