/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a4a24658-0212-4797-bb5d-298ec52f147a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Q9eVjbW8k",
    "aws_user_pools_web_client_id": "55946l32k0ade7f232mu2odbh5",
    "oauth": {}
};


export default awsmobile;
