/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a4a24658-0212-4797-bb5d-298ec52f147a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Q9eVjbW8k",
    "aws_user_pools_web_client_id": "55946l32k0ade7f232mu2odbh5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xqaj5egv5rcipbc47jsvuygcue.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yd4hzfpitvah5nihcvocpanp4q",
    "aws_user_files_s3_bucket": "awsdvacertf1fcce517132482686d3e8e5c2e71b8a151440-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
